##Signup/Loginn - VERY FIRST THING 
    ## Browse Games
    ## Find Your Perfect Game
    ## View your saved games
    ###???? try to view top 10 list for games 
class Cli  
    puts "Bored Games"
    puts "When you dont know what to play, let us help you!" 

    #LAYOUT
    #IS THIS YOUR FIRST TIME HERE?
    #IF SO TAKE TO SIGN UP, IF NOT TAKE TO 'LOGIN' SCREEN

    #SIGNUP -- PROMPT.ASK TO GET FIRST NAME AND USERNAME
    #LOGGING -- INPUT THEIR USERNAME AND SET THE USER AND USERNAME; CAN LIKELY USE FINDBY 

    #AFTER LOGGING IN HAVE OPTIONS:
        #LET US RANDOMLY SELECT A GAME!
        #DO THE QUIZ TO HELP US SELECT GAME 
            #HOW MANY PLAYERS DO YOU HAVE?
            #WHAT IS YOUR TIME LIMIT?
            #HOW CHALLENGING WOULD YOU LIKE THE GAME TO BE?
            #LOADING BAR? MAYBE WITH LIKE LITTLE BOARD GAMES LIKE THEY HAD TACOS??
            #OUTPUT THE GAME, OR SAY SORRY AT THIS TIME NO GAME MATCHES YOUR REQUIREMENTS AND THEN BIG SAD FACE
            
        #ADD GAME TO THE GAME LIBRARY
        #BROWSE ALL CURRENT GAMES
        #FINAL ADDITION I WOULD LIKE TO TRY WOULD BE TO IMPLEMENT AN API THAT WOULD SHOW THE TOP THEN HOTTEST GAMES OUT ATM,
        #BUT THIS IS THE REACH GOAL LOL 

        




end